"""
Prepare canonical transcript files and a custom lexicon for MFA.

Input:
    data/transcript/*.txt
    data/audio/*.wav

Output:
    data/audio/*.txt
    custom_mfa.dict
"""

from __future__ import annotations

import argparse
from pathlib import Path

from phoneme_utils import (
    compare_phones_to_mfa,
    load_dictionary,
    read_transcript,
    word_to_compare_phones,
)


def find_matching_audio_stem(audio_dir: Path, stem: str) -> str:
    exact = audio_dir / f"{stem}.wav"
    if exact.exists():
        return stem

    lower_stem = stem.lower()
    for path in audio_dir.glob("*.wav"):
        if path.stem.lower() == lower_stem:
            return path.stem
    return stem


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare transcript text and lexicon for MFA.")
    parser.add_argument("--transcript-dir", default="data/transcript")
    parser.add_argument("--audio-dir", default="data/audio")
    parser.add_argument("--dictionary", default=None, help="Optional word-to-phone lexicon.")
    parser.add_argument("--dict-out", default="custom_mfa.dict")
    args = parser.parse_args()

    transcript_dir = Path(args.transcript_dir)
    audio_dir = Path(args.audio_dir)
    dict_out = Path(args.dict_out)
    dictionary = load_dictionary(Path(args.dictionary)) if args.dictionary else {}
    audio_dir.mkdir(parents=True, exist_ok=True)

    transcript_files = sorted(transcript_dir.glob("*.txt"))
    if not transcript_files:
        print(f"ERROR: no transcript files found in {transcript_dir}")
        return

    lexicon: dict[str, list[str]] = {}
    fallback_words: set[str] = set()
    prepared_files = 0

    for transcript_path in transcript_files:
        words = read_transcript(transcript_path)
        if not words:
            print(f"Skip {transcript_path}: empty transcript after normalization")
            continue

        output_stem = find_matching_audio_stem(audio_dir, transcript_path.stem)
        output_path = audio_dir / f"{output_stem}.txt"
        output_path.write_text(" ".join(words), encoding="utf-8")

        for word in words:
            phones, used_fallback = word_to_compare_phones(word, dictionary)
            lexicon[word] = compare_phones_to_mfa(phones)
            if used_fallback:
                fallback_words.add(word)

        prepared_files += 1
        print(f"Wrote MFA transcript: {output_path}")

    with dict_out.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/03_prepare_mfa.py from data/transcript/*.txt\n")
        f.write("# Format: word<TAB>MFA phones\n")
        for word in sorted(lexicon):
            f.write(f"{word}\t{' '.join(lexicon[word])}\n")

    print(f"\nPrepared {prepared_files} transcript files for MFA.")
    print(f"Wrote MFA dictionary: {dict_out}")
    if fallback_words:
        words_str = ", ".join(sorted(fallback_words))
        print(f"INFO: used fallback G2P for {len(fallback_words)} word(s): {words_str}")
    print("\nNext:")
    print(f"mfa align --clean {audio_dir} {dict_out} english_mfa data/aligned")


if __name__ == "__main__":
    main()
